== Appendix A: Relationship to Other Standards

JSR-181 relies on Java standards, Web Services standards, XML standards
and Internet standards.

Java Language standards: J2SE 5.0 is needed for the JSR-175 defined
Metadata Facility.

Java runtime and container standards: JSR-181 does not define a
container or runtime environment – implementers provide tools to map the
Java classes to specific runtime environments. The functionality of the
Jakarta containers is assumed. The features provided by JAX-WS 2.0 are
needed for the Web Services runtime as well as the mapping conventions;
Java to XML/WSDL and WSDL/XML to Java. An optional mapping to JSR-109
deployment descriptors is provided in JSR-181.

Web Services standards: SOAP 1.1 and WSDL 1.1 are used to describe the
Web Service and define the XML messages.

XML standards: The XML language and the XML Schema 1.0 are an integral
part of JSR-181.

Internet standards: HTTP and HTTP/S provide basic protocols for Web
Services.

== Appendix B: Handler Chain Configuration File Schema

The XML Schema for the handler chain configuration file is described at
[.underline]#http://java.sun.com/xml/ns/javaee/javaee web services
metadata handler 2 0.xsd#

== Appendix C: Non-Normative Examples of Alternate Binding Annotations

This section defines non-normative examples of annotations for bindings
to non-standard protocols and transports.

=== C.1 Annotation Name: HttpGetBinding

==== C.1.1 Description

Non-normative example of an alternate binding – in this case a raw HTTP
binding as specified in WSDL 1.1 [7] section 4.

[cols=",,",]
|===
a|
Member-Value

a|
Meaning

a|
Default

a|
location

a|
The location of the HTTP GET endpoint. When defined at the class level,
defines as the base URI for all operations on the service. When defined
at the method level, defines the URI for a particular operation relative
to the base URI for the service.

a|
Implementation-defined

|===

==== C.1.2 Annotation Type Definition

[source,java]
----
@Target({TYPE, METHOD})
public @interface HttpGetBinding {
   String location() default "";
}
----

==== C.1.3 Example

[source,java]
----
@WebService
@HttpGetBinding(location="MyWebServices")
public class MyWebServiceImpl { 
   @WebMethod 
   @HttpGetBinding(location="ExampleOperation") 
   public void myOperation() { 
   }
};
----

== Appendix D: Change Log

Version 2.1

* Changed specification version and license information.
* Updated Handler Chain Configuration File Schema in Appendix B to fix
errors, add missing elements, and make it valid.
* Updated Section 3.1 to clarify the explanation of when an SEI is
implicitly defined by an implementation bean. The revised text refers to
the appropriate section 3.3 in the JAX-WS 2.0 specification for the
actual SEI rules.
* Updated the table in Section 4.4.1 describing the default "name" member
value of the javax.jws.WebParam annotation to resolve the issue reported
in [.underline]#https://jax-ws.dev.java.net/issues/show_bug.cgi?id=710[
https://jax-ws.dev.java.net/issues/show_bug.cgi?id=710]#. The
requirement to specify a name for "document" style, parameter style
"BARE", and mode "OUT" or "INOUT" is lifted and default rules are
defined. This change is consistent with section 3.6.2.2 of the JAX-WS
2.0 specification.

Version 2.0

* Added @WebResult.header.
* A document "bare" style operation can have a void return type and a
Holder as a parameter. The Holder of course would have to be INOUT. It
could also have 2 parameters one IN and one OUT.
* Changed @SOAPBinding to be configurable on a per operation basis rather
than on the entire interface.
* Made @HandlerChain.name and @SOAPMessageHandlers deprecated.
* Added support for JAX-WS.
* Updated section 3.1 Service Implementation Bean, Item 6 to state that
exposing all public methods if not @WebMethod annotations are declared
to include consideration of annotation inheritence.
* Changed default of @WebResult.name to @WebMethod.operationName +
"Response" for Doc/lit/bare operations.
* Clarified @WebService.targetNamespace usage
* Clarified @WebParam.mode usage.
* Added @WebMethod.exclude.
* Explicitly stated that if an implementation bean references an endpoint
interface, it must implement all the methods in the service endpoint
interface.
* Changed @WebParam.name to default to arg0, arg1, etc (based on position
in the method signature).
* Added @WebParam.partName and @WebResult.partName to specify part name
used in the binding.
* Added requirement that the name for headers must be unique with an
operation.
* Clairified that a target namespace of "" maps to the empty namespace,
not the web service namespace.
* For doc/lit bare, require that any INOUT or OUT parameters must have a
@WebParam.name specified to avoid name clashes with the input parameter.


* Added @WebService.portName for the wsdl:port
* Updated Handler schema
* Added document/literal example to Using JSR-181 annotation to affect the
shape of the WSDL
* Included various editorial changes.

Version 0.9.4

* Allowing @HandlerChain and @SOAPMessageHandler on implementation when an
endpointInterface is used.

Version 0.9.3

* Using RFC 2119 Keyword convention.
* Added Retention annotation to spec annotation definitions.
* Fixed various Java and XML syntax errors.
* Changed Implementation Bean to expose all public method by default.
* WSDL generation is REQUIRED.
* Clarified support for Start with WSDL, and Start with WSDL and Java
development modes as OPTIONAL.
* Clarified [.underline]#mailto:@HandlerChain.file[ @HandlerChain.file]#
attribute syntax and processing requirements.

Version 0.9.2

* Removed security annotations as these will be defined by JSR-250 –
Common Annotations.

Version 0.9.1

* Changed default name of @WebResult to be "return" instead of "result".
* Fixed various Java and XML syntax errors.
